name: Targeting Service CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: fiap-tech-challenge-devops/reusable-workflows/.github/workflows/python-ci.yml@v2.1.0

    with:
      python-version: "3.9"
      ecr-repository: "togglemaster/targeting-service"
      aws-region: "us-east-1"

    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
